
import matplotlib.pyplot as plt 
import pandas as pd 
import numpy as np 
import re
import seaborn as sb
def plot_coverage(file_path: str, cutoff: int = 10000)->pd.DataFrame:
    """
    args: 
    1) file_path - path to  coverage file generated by Bedtools module
    2) cutoff - value to check what % of samples are above
    returns:
    1) data-frame representation of input file. 
    """
    file = open(file_path)
    d = {'strand':[], "position": [], "coverage":[]}
    pattern = r'\S+'
    for line in file:
        match = re.findall(pattern, line)
        d['strand'].append(match[0])
        d["position"].append(float(match[1]))
        d["coverage"].append(float(match[2]))
    d['position'] = np.array(d["position"])
    d["coverage"] = np.array(d["coverage"])
    df = pd.DataFrame(d)
    frac = np.sum(df["coverage"]>cutoff)/df["coverage"].shape[0]
    sb.histplot(d["coverage"], binwidth=150)
    plt.annotate(text="{0}% of samples have coverage above {1}".format(round(frac*100, 5), cutoff), xy=(.70,1.01), xycoords = 'axes fraction')
    plt.xlabel('coverage')
    plt.ylabel('count')
    plt.xlim(0, np.mean(df["coverage"])*(1.5))
    plt.title("Coverage frequency")
    plt.show()
    return d

file_path = 'data/ERR3239481/ERR3239481_rDNA_coverage.txt'
plot_coverage(file_path=file_path)

"""
TODO:
1) look for a python package to parse .vcf files 
2) figure out how to visualize that data. 
"""